// epic=04_billing, us=01_subscription_management
// Billing service for subscription and payment management

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/billing.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscription tier enum
type SubscriptionTier int32

const (
	SubscriptionTier_TIER_UNSPECIFIED  SubscriptionTier = 0
	SubscriptionTier_TIER_FREE         SubscriptionTier = 1
	SubscriptionTier_TIER_STARTER      SubscriptionTier = 2
	SubscriptionTier_TIER_PROFESSIONAL SubscriptionTier = 3
	SubscriptionTier_TIER_BUSINESS     SubscriptionTier = 4
)

// Enum value maps for SubscriptionTier.
var (
	SubscriptionTier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_FREE",
		2: "TIER_STARTER",
		3: "TIER_PROFESSIONAL",
		4: "TIER_BUSINESS",
	}
	SubscriptionTier_value = map[string]int32{
		"TIER_UNSPECIFIED":  0,
		"TIER_FREE":         1,
		"TIER_STARTER":      2,
		"TIER_PROFESSIONAL": 3,
		"TIER_BUSINESS":     4,
	}
)

func (x SubscriptionTier) Enum() *SubscriptionTier {
	p := new(SubscriptionTier)
	*p = x
	return p
}

func (x SubscriptionTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_billing_proto_enumTypes[0].Descriptor()
}

func (SubscriptionTier) Type() protoreflect.EnumType {
	return &file_proto_billing_proto_enumTypes[0]
}

func (x SubscriptionTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionTier.Descriptor instead.
func (SubscriptionTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

// Subscription status enum
type SubscriptionStatus int32

const (
	SubscriptionStatus_STATUS_UNSPECIFIED SubscriptionStatus = 0
	SubscriptionStatus_STATUS_ACTIVE      SubscriptionStatus = 1
	SubscriptionStatus_STATUS_PENDING     SubscriptionStatus = 2
	SubscriptionStatus_STATUS_CANCELED    SubscriptionStatus = 3
	SubscriptionStatus_STATUS_EXPIRED     SubscriptionStatus = 4
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_PENDING",
		3: "STATUS_CANCELED",
		4: "STATUS_EXPIRED",
	}
	SubscriptionStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_PENDING":     2,
		"STATUS_CANCELED":    3,
		"STATUS_EXPIRED":     4,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_billing_proto_enumTypes[1].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_proto_billing_proto_enumTypes[1]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{1}
}

// Payment provider enum
type PaymentProvider int32

const (
	PaymentProvider_PROVIDER_UNSPECIFIED PaymentProvider = 0
	PaymentProvider_PROVIDER_YOOKASSA    PaymentProvider = 1
	PaymentProvider_PROVIDER_STRIPE      PaymentProvider = 2
)

// Enum value maps for PaymentProvider.
var (
	PaymentProvider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_YOOKASSA",
		2: "PROVIDER_STRIPE",
	}
	PaymentProvider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_YOOKASSA":    1,
		"PROVIDER_STRIPE":      2,
	}
)

func (x PaymentProvider) Enum() *PaymentProvider {
	p := new(PaymentProvider)
	*p = x
	return p
}

func (x PaymentProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_billing_proto_enumTypes[2].Descriptor()
}

func (PaymentProvider) Type() protoreflect.EnumType {
	return &file_proto_billing_proto_enumTypes[2]
}

func (x PaymentProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProvider.Descriptor instead.
func (PaymentProvider) EnumDescriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{2}
}

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCESS     PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCESS",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCESS":     2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_billing_proto_enumTypes[3].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_billing_proto_enumTypes[3]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{3}
}

// Subscription plan
type SubscriptionPlan struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tier                    SubscriptionTier       `protobuf:"varint,2,opt,name=tier,proto3,enum=billing.SubscriptionTier" json:"tier,omitempty"`
	Name                    string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description             string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PriceKopeks             int64                  `protobuf:"varint,5,opt,name=price_kopeks,json=priceKopeks,proto3" json:"price_kopeks,omitempty"` // price in Russian kopeks (100 kopeks = 1 ruble)
	BillingPeriodDays       int32                  `protobuf:"varint,6,opt,name=billing_period_days,json=billingPeriodDays,proto3" json:"billing_period_days,omitempty"`
	MaxMonitors             int32                  `protobuf:"varint,7,opt,name=max_monitors,json=maxMonitors,proto3" json:"max_monitors,omitempty"`
	MinCheckIntervalSeconds int32                  `protobuf:"varint,8,opt,name=min_check_interval_seconds,json=minCheckIntervalSeconds,proto3" json:"min_check_interval_seconds,omitempty"`
	Features                []*Feature             `protobuf:"bytes,9,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SubscriptionPlan) Reset() {
	*x = SubscriptionPlan{}
	mi := &file_proto_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPlan) ProtoMessage() {}

func (x *SubscriptionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPlan.ProtoReflect.Descriptor instead.
func (*SubscriptionPlan) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionPlan) GetTier() SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return SubscriptionTier_TIER_UNSPECIFIED
}

func (x *SubscriptionPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubscriptionPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubscriptionPlan) GetPriceKopeks() int64 {
	if x != nil {
		return x.PriceKopeks
	}
	return 0
}

func (x *SubscriptionPlan) GetBillingPeriodDays() int32 {
	if x != nil {
		return x.BillingPeriodDays
	}
	return 0
}

func (x *SubscriptionPlan) GetMaxMonitors() int32 {
	if x != nil {
		return x.MaxMonitors
	}
	return 0
}

func (x *SubscriptionPlan) GetMinCheckIntervalSeconds() int32 {
	if x != nil {
		return x.MinCheckIntervalSeconds
	}
	return 0
}

func (x *SubscriptionPlan) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

// Feature included in plan
type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_proto_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Feature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Subscription entity
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tier          SubscriptionTier       `protobuf:"varint,3,opt,name=tier,proto3,enum=billing.SubscriptionTier" json:"tier,omitempty"`
	Status        SubscriptionStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=billing.SubscriptionStatus" json:"status,omitempty"`
	PlanId        string                 `protobuf:"bytes,5,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CanceledAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	AutoRenew     bool                   `protobuf:"varint,9,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetTier() SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return SubscriptionTier_TIER_UNSPECIFIED
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_STATUS_UNSPECIFIED
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Subscription) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Subscription) GetCanceledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CanceledAt
	}
	return nil
}

func (x *Subscription) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

// Payment entity
type Payment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId    string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Provider          PaymentProvider        `protobuf:"varint,4,opt,name=provider,proto3,enum=billing.PaymentProvider" json:"provider,omitempty"`
	ProviderPaymentId string                 `protobuf:"bytes,5,opt,name=provider_payment_id,json=providerPaymentId,proto3" json:"provider_payment_id,omitempty"`
	Status            PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=billing.PaymentStatus" json:"status,omitempty"`
	AmountKopeks      int64                  `protobuf:"varint,7,opt,name=amount_kopeks,json=amountKopeks,proto3" json:"amount_kopeks,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_proto_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Payment) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_PROVIDER_UNSPECIFIED
}

func (x *Payment) GetProviderPaymentId() string {
	if x != nil {
		return x.ProviderPaymentId
	}
	return ""
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetAmountKopeks() int64 {
	if x != nil {
		return x.AmountKopeks
	}
	return 0
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_proto_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubscriptionPlans struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*SubscriptionPlan    `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPlans) Reset() {
	*x = SubscriptionPlans{}
	mi := &file_proto_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPlans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPlans) ProtoMessage() {}

func (x *SubscriptionPlans) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPlans.ProtoReflect.Descriptor instead.
func (*SubscriptionPlans) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionPlans) GetPlans() []*SubscriptionPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type CreateCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,3,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutRequest) Reset() {
	*x = CreateCheckoutRequest{}
	mi := &file_proto_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutRequest) ProtoMessage() {}

func (x *CreateCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCheckoutRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateCheckoutRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{7}
}

func (x *CheckoutResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CheckoutResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetPaymentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentHistoryRequest) Reset() {
	*x = GetPaymentHistoryRequest{}
	mi := &file_proto_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentHistoryRequest) ProtoMessage() {}

func (x *GetPaymentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPaymentHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPaymentHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PaymentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentHistoryResponse) Reset() {
	*x = PaymentHistoryResponse{}
	mi := &file_proto_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentHistoryResponse) ProtoMessage() {}

func (x *PaymentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentHistoryResponse.ProtoReflect.Descriptor instead.
func (*PaymentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentHistoryResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *PaymentHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaymentHistoryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaymentHistoryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CancelReason  string                 `protobuf:"bytes,2,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_proto_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{10}
}

func (x *CancelSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type WebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookRequest) Reset() {
	*x = WebhookRequest{}
	mi := &file_proto_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookRequest) ProtoMessage() {}

func (x *WebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookRequest.ProtoReflect.Descriptor instead.
func (*WebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_proto_rawDescGZIP(), []int{11}
}

func (x *WebhookRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WebhookRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_proto_billing_proto protoreflect.FileDescriptor

const file_proto_billing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/billing.proto\x12\abilling\x1a\x12proto/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xe8\x02\n" +
	"\x10SubscriptionPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x19.billing.SubscriptionTierR\x04tier\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\fprice_kopeks\x18\x05 \x01(\x03R\vpriceKopeks\x12.\n" +
	"\x13billing_period_days\x18\x06 \x01(\x05R\x11billingPeriodDays\x12!\n" +
	"\fmax_monitors\x18\a \x01(\x05R\vmaxMonitors\x12;\n" +
	"\x1amin_check_interval_seconds\x18\b \x01(\x05R\x17minCheckIntervalSeconds\x12,\n" +
	"\bfeatures\x18\t \x03(\v2\x10.billing.FeatureR\bfeatures\"O\n" +
	"\aFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x86\x03\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12-\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x19.billing.SubscriptionTierR\x04tier\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.billing.SubscriptionStatusR\x06status\x12\x17\n" +
	"\aplan_id\x18\x05 \x01(\tR\x06planId\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12;\n" +
	"\vcanceled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"canceledAt\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\t \x01(\bR\tautoRenew\"\x85\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x124\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x18.billing.PaymentProviderR\bprovider\x12.\n" +
	"\x13provider_payment_id\x18\x05 \x01(\tR\x11providerPaymentId\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.billing.PaymentStatusR\x06status\x12#\n" +
	"\ramount_kopeks\x18\a \x01(\x03R\famountKopeks\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12:\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1e.billing.Payment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x16GetSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x11SubscriptionPlans\x12/\n" +
	"\x05plans\x18\x01 \x03(\v2\x19.billing.SubscriptionPlanR\x05plans\"h\n" +
	"\x15CreateCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1d\n" +
	"\n" +
	"return_url\x18\x03 \x01(\tR\treturnUrl\"T\n" +
	"\x10CheckoutResponse\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"d\n" +
	"\x18GetPaymentHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x8d\x01\n" +
	"\x16PaymentHistoryResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.billing.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"Y\n" +
	"\x19CancelSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rcancel_reason\x18\x02 \x01(\tR\fcancelReason\"\xc6\x01\n" +
	"\x0eWebhookRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12>\n" +
	"\apayload\x18\x02 \x03(\v2$.billing.WebhookRequest.PayloadEntryR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*s\n" +
	"\x10SubscriptionTier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTIER_FREE\x10\x01\x12\x10\n" +
	"\fTIER_STARTER\x10\x02\x12\x15\n" +
	"\x11TIER_PROFESSIONAL\x10\x03\x12\x11\n" +
	"\rTIER_BUSINESS\x10\x04*|\n" +
	"\x12SubscriptionStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x02\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_EXPIRED\x10\x04*W\n" +
	"\x0fPaymentProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PROVIDER_YOOKASSA\x10\x01\x12\x13\n" +
	"\x0fPROVIDER_STRIPE\x10\x02*\x9f\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x042\xd4\x05\n" +
	"\x0eBillingService\x12`\n" +
	"\x14GetSubscriptionPlans\x12\r.common.Empty\x1a\x1a.billing.SubscriptionPlans\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/billing/plans\x12z\n" +
	"\x0fGetSubscription\x12\x1f.billing.GetSubscriptionRequest\x1a\x15.billing.Subscription\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/billing/subscriptions/{user_id}\x12p\n" +
	"\x0eCreateCheckout\x12\x1e.billing.CreateCheckoutRequest\x1a\x19.billing.CheckoutResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/billing/checkout\x12\x83\x01\n" +
	"\x11GetPaymentHistory\x12!.billing.GetPaymentHistoryRequest\x1a\x1f.billing.PaymentHistoryResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/billing/payments/{user_id}\x12\x82\x01\n" +
	"\x12CancelSubscription\x12\".billing.CancelSubscriptionRequest\x1a\r.common.Empty\"9\x82\xd3\xe4\x93\x023:\x01*\"./api/v1/billing/subscriptions/{user_id}/cancel\x12g\n" +
	"\rHandleWebhook\x12\x17.billing.WebhookRequest\x1a\r.common.Empty\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/billing/webhooks/{provider}B\x1dZ\x1bgithub.com/raul/monitor/apib\x06proto3"

var (
	file_proto_billing_proto_rawDescOnce sync.Once
	file_proto_billing_proto_rawDescData []byte
)

func file_proto_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)))
	})
	return file_proto_billing_proto_rawDescData
}

var file_proto_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_billing_proto_goTypes = []any{
	(SubscriptionTier)(0),             // 0: billing.SubscriptionTier
	(SubscriptionStatus)(0),           // 1: billing.SubscriptionStatus
	(PaymentProvider)(0),              // 2: billing.PaymentProvider
	(PaymentStatus)(0),                // 3: billing.PaymentStatus
	(*SubscriptionPlan)(nil),          // 4: billing.SubscriptionPlan
	(*Feature)(nil),                   // 5: billing.Feature
	(*Subscription)(nil),              // 6: billing.Subscription
	(*Payment)(nil),                   // 7: billing.Payment
	(*GetSubscriptionRequest)(nil),    // 8: billing.GetSubscriptionRequest
	(*SubscriptionPlans)(nil),         // 9: billing.SubscriptionPlans
	(*CreateCheckoutRequest)(nil),     // 10: billing.CreateCheckoutRequest
	(*CheckoutResponse)(nil),          // 11: billing.CheckoutResponse
	(*GetPaymentHistoryRequest)(nil),  // 12: billing.GetPaymentHistoryRequest
	(*PaymentHistoryResponse)(nil),    // 13: billing.PaymentHistoryResponse
	(*CancelSubscriptionRequest)(nil), // 14: billing.CancelSubscriptionRequest
	(*WebhookRequest)(nil),            // 15: billing.WebhookRequest
	nil,                               // 16: billing.Payment.MetadataEntry
	nil,                               // 17: billing.WebhookRequest.PayloadEntry
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*Empty)(nil),                     // 19: common.Empty
}
var file_proto_billing_proto_depIdxs = []int32{
	0,  // 0: billing.SubscriptionPlan.tier:type_name -> billing.SubscriptionTier
	5,  // 1: billing.SubscriptionPlan.features:type_name -> billing.Feature
	0,  // 2: billing.Subscription.tier:type_name -> billing.SubscriptionTier
	1,  // 3: billing.Subscription.status:type_name -> billing.SubscriptionStatus
	18, // 4: billing.Subscription.started_at:type_name -> google.protobuf.Timestamp
	18, // 5: billing.Subscription.expires_at:type_name -> google.protobuf.Timestamp
	18, // 6: billing.Subscription.canceled_at:type_name -> google.protobuf.Timestamp
	2,  // 7: billing.Payment.provider:type_name -> billing.PaymentProvider
	3,  // 8: billing.Payment.status:type_name -> billing.PaymentStatus
	18, // 9: billing.Payment.created_at:type_name -> google.protobuf.Timestamp
	18, // 10: billing.Payment.updated_at:type_name -> google.protobuf.Timestamp
	16, // 11: billing.Payment.metadata:type_name -> billing.Payment.MetadataEntry
	4,  // 12: billing.SubscriptionPlans.plans:type_name -> billing.SubscriptionPlan
	7,  // 13: billing.PaymentHistoryResponse.payments:type_name -> billing.Payment
	17, // 14: billing.WebhookRequest.payload:type_name -> billing.WebhookRequest.PayloadEntry
	19, // 15: billing.BillingService.GetSubscriptionPlans:input_type -> common.Empty
	8,  // 16: billing.BillingService.GetSubscription:input_type -> billing.GetSubscriptionRequest
	10, // 17: billing.BillingService.CreateCheckout:input_type -> billing.CreateCheckoutRequest
	12, // 18: billing.BillingService.GetPaymentHistory:input_type -> billing.GetPaymentHistoryRequest
	14, // 19: billing.BillingService.CancelSubscription:input_type -> billing.CancelSubscriptionRequest
	15, // 20: billing.BillingService.HandleWebhook:input_type -> billing.WebhookRequest
	9,  // 21: billing.BillingService.GetSubscriptionPlans:output_type -> billing.SubscriptionPlans
	6,  // 22: billing.BillingService.GetSubscription:output_type -> billing.Subscription
	11, // 23: billing.BillingService.CreateCheckout:output_type -> billing.CheckoutResponse
	13, // 24: billing.BillingService.GetPaymentHistory:output_type -> billing.PaymentHistoryResponse
	19, // 25: billing.BillingService.CancelSubscription:output_type -> common.Empty
	19, // 26: billing.BillingService.HandleWebhook:output_type -> common.Empty
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_billing_proto_init() }
func file_proto_billing_proto_init() {
	if File_proto_billing_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_proto_rawDesc), len(file_proto_billing_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_proto_depIdxs,
		EnumInfos:         file_proto_billing_proto_enumTypes,
		MessageInfos:      file_proto_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_proto = out.File
	file_proto_billing_proto_goTypes = nil
	file_proto_billing_proto_depIdxs = nil
}
