// epic=common, us=shared_types
// Common types and messages shared across services

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User tier enum
type UserTier int32

const (
	UserTier_TIER_UNSPECIFIED  UserTier = 0
	UserTier_TIER_FREE         UserTier = 1
	UserTier_TIER_STARTER      UserTier = 2
	UserTier_TIER_PROFESSIONAL UserTier = 3
	UserTier_TIER_BUSINESS     UserTier = 4
)

// Enum value maps for UserTier.
var (
	UserTier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_FREE",
		2: "TIER_STARTER",
		3: "TIER_PROFESSIONAL",
		4: "TIER_BUSINESS",
	}
	UserTier_value = map[string]int32{
		"TIER_UNSPECIFIED":  0,
		"TIER_FREE":         1,
		"TIER_STARTER":      2,
		"TIER_PROFESSIONAL": 3,
		"TIER_BUSINESS":     4,
	}
)

func (x UserTier) Enum() *UserTier {
	p := new(UserTier)
	*p = x
	return p
}

func (x UserTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[0].Descriptor()
}

func (UserTier) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[0]
}

func (x UserTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserTier.Descriptor instead.
func (UserTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

// Auth type enum
type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED  AuthType = 0
	AuthType_AUTH_TYPE_PASSWORD     AuthType = 1
	AuthType_AUTH_TYPE_OAUTH_GOOGLE AuthType = 2
	AuthType_AUTH_TYPE_OAUTH_GITHUB AuthType = 3
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_PASSWORD",
		2: "AUTH_TYPE_OAUTH_GOOGLE",
		3: "AUTH_TYPE_OAUTH_GITHUB",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED":  0,
		"AUTH_TYPE_PASSWORD":     1,
		"AUTH_TYPE_OAUTH_GOOGLE": 2,
		"AUTH_TYPE_OAUTH_GITHUB": 3,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_enumTypes[1].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_proto_common_proto_enumTypes[1]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

// User represents a user entity
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	LoginAttempts int32                  `protobuf:"varint,8,opt,name=login_attempts,json=loginAttempts,proto3" json:"login_attempts,omitempty"`
	LockedUntil   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *User) GetLoginAttempts() int32 {
	if x != nil {
		return x.LoginAttempts
	}
	return 0
}

func (x *User) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

// Session represents a user session
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthType      string                 `protobuf:"bytes,3,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *Session) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RefreshToken represents a refresh token
type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthType      string                 `protobuf:"bytes,3,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,6,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefreshToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshToken) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *RefreshToken) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RefreshToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RefreshToken) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

// OAuthAccount represents a linked OAuth account
type OAuthAccount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUserId string                 `protobuf:"bytes,4,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	Email          string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Metadata       string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OAuthAccount) Reset() {
	*x = OAuthAccount{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthAccount) ProtoMessage() {}

func (x *OAuthAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthAccount.ProtoReflect.Descriptor instead.
func (*OAuthAccount) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *OAuthAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuthAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OAuthAccount) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthAccount) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

func (x *OAuthAccount) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OAuthAccount) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *OAuthAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Tier limits configuration
type TierLimits struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxMonitors             int32                  `protobuf:"varint,1,opt,name=max_monitors,json=maxMonitors,proto3" json:"max_monitors,omitempty"`
	MinCheckIntervalSeconds int32                  `protobuf:"varint,2,opt,name=min_check_interval_seconds,json=minCheckIntervalSeconds,proto3" json:"min_check_interval_seconds,omitempty"`
	MaxAlertsPerDay         int32                  `protobuf:"varint,3,opt,name=max_alerts_per_day,json=maxAlertsPerDay,proto3" json:"max_alerts_per_day,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TierLimits) Reset() {
	*x = TierLimits{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierLimits) ProtoMessage() {}

func (x *TierLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierLimits.ProtoReflect.Descriptor instead.
func (*TierLimits) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *TierLimits) GetMaxMonitors() int32 {
	if x != nil {
		return x.MaxMonitors
	}
	return 0
}

func (x *TierLimits) GetMinCheckIntervalSeconds() int32 {
	if x != nil {
		return x.MinCheckIntervalSeconds
	}
	return 0
}

func (x *TierLimits) GetMaxAlertsPerDay() int32 {
	if x != nil {
		return x.MaxAlertsPerDay
	}
	return 0
}

// Tier limits for all tiers
type AllTierLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Free          *TierLimits            `protobuf:"bytes,1,opt,name=free,proto3" json:"free,omitempty"`
	Starter       *TierLimits            `protobuf:"bytes,2,opt,name=starter,proto3" json:"starter,omitempty"`
	Professional  *TierLimits            `protobuf:"bytes,3,opt,name=professional,proto3" json:"professional,omitempty"`
	Business      *TierLimits            `protobuf:"bytes,4,opt,name=business,proto3" json:"business,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTierLimits) Reset() {
	*x = AllTierLimits{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTierLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTierLimits) ProtoMessage() {}

func (x *AllTierLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTierLimits.ProtoReflect.Descriptor instead.
func (*AllTierLimits) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *AllTierLimits) GetFree() *TierLimits {
	if x != nil {
		return x.Free
	}
	return nil
}

func (x *AllTierLimits) GetStarter() *TierLimits {
	if x != nil {
		return x.Starter
	}
	return nil
}

func (x *AllTierLimits) GetProfessional() *TierLimits {
	if x != nil {
		return x.Professional
	}
	return nil
}

func (x *AllTierLimits) GetBusiness() *TierLimits {
	if x != nil {
		return x.Business
	}
	return nil
}

// Error response structure
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Empty request
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{7}
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rlast_login_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\x12%\n" +
	"\x0elogin_attempts\x18\b \x01(\x05R\rloginAttempts\x12=\n" +
	"\flocked_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\"\x83\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tauth_type\x18\x03 \x01(\tR\bauthType\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xcd\x01\n" +
	"\fRefreshToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tauth_type\x18\x03 \x01(\tR\bauthType\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x06 \x01(\bR\tisRevoked\"\xea\x01\n" +
	"\fOAuthAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12(\n" +
	"\x10provider_user_id\x18\x04 \x01(\tR\x0eproviderUserId\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x99\x01\n" +
	"\n" +
	"TierLimits\x12!\n" +
	"\fmax_monitors\x18\x01 \x01(\x05R\vmaxMonitors\x12;\n" +
	"\x1amin_check_interval_seconds\x18\x02 \x01(\x05R\x17minCheckIntervalSeconds\x12+\n" +
	"\x12max_alerts_per_day\x18\x03 \x01(\x05R\x0fmaxAlertsPerDay\"\xcd\x01\n" +
	"\rAllTierLimits\x12&\n" +
	"\x04free\x18\x01 \x01(\v2\x12.common.TierLimitsR\x04free\x12,\n" +
	"\astarter\x18\x02 \x01(\v2\x12.common.TierLimitsR\astarter\x126\n" +
	"\fprofessional\x18\x03 \x01(\v2\x12.common.TierLimitsR\fprofessional\x12.\n" +
	"\bbusiness\x18\x04 \x01(\v2\x12.common.TierLimitsR\bbusiness\"\xd6\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".common.ErrorResponse.DetailsEntryR\adetails\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty*k\n" +
	"\bUserTier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTIER_FREE\x10\x01\x12\x10\n" +
	"\fTIER_STARTER\x10\x02\x12\x15\n" +
	"\x11TIER_PROFESSIONAL\x10\x03\x12\x11\n" +
	"\rTIER_BUSINESS\x10\x04*u\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AUTH_TYPE_PASSWORD\x10\x01\x12\x1a\n" +
	"\x16AUTH_TYPE_OAUTH_GOOGLE\x10\x02\x12\x1a\n" +
	"\x16AUTH_TYPE_OAUTH_GITHUB\x10\x03B\x1dZ\x1bgithub.com/raul/monitor/apib\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_common_proto_goTypes = []any{
	(UserTier)(0),                 // 0: common.UserTier
	(AuthType)(0),                 // 1: common.AuthType
	(*User)(nil),                  // 2: common.User
	(*Session)(nil),               // 3: common.Session
	(*RefreshToken)(nil),          // 4: common.RefreshToken
	(*OAuthAccount)(nil),          // 5: common.OAuthAccount
	(*TierLimits)(nil),            // 6: common.TierLimits
	(*AllTierLimits)(nil),         // 7: common.AllTierLimits
	(*ErrorResponse)(nil),         // 8: common.ErrorResponse
	(*Empty)(nil),                 // 9: common.Empty
	nil,                           // 10: common.ErrorResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_common_proto_depIdxs = []int32{
	11, // 0: common.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: common.User.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: common.User.last_login_at:type_name -> google.protobuf.Timestamp
	11, // 3: common.User.locked_until:type_name -> google.protobuf.Timestamp
	11, // 4: common.Session.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: common.Session.expires_at:type_name -> google.protobuf.Timestamp
	11, // 6: common.RefreshToken.expires_at:type_name -> google.protobuf.Timestamp
	11, // 7: common.OAuthAccount.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: common.AllTierLimits.free:type_name -> common.TierLimits
	6,  // 9: common.AllTierLimits.starter:type_name -> common.TierLimits
	6,  // 10: common.AllTierLimits.professional:type_name -> common.TierLimits
	6,  // 11: common.AllTierLimits.business:type_name -> common.TierLimits
	10, // 12: common.ErrorResponse.details:type_name -> common.ErrorResponse.DetailsEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
