// epic=05_notification_templates, us=01_template_management
// Notification Template service for managing alert notification templates

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/notification_template.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationTemplateService_CreateTemplate_FullMethodName        = "/notification_template.NotificationTemplateService/CreateTemplate"
	NotificationTemplateService_GetTemplate_FullMethodName           = "/notification_template.NotificationTemplateService/GetTemplate"
	NotificationTemplateService_ListTemplates_FullMethodName         = "/notification_template.NotificationTemplateService/ListTemplates"
	NotificationTemplateService_UpdateTemplate_FullMethodName        = "/notification_template.NotificationTemplateService/UpdateTemplate"
	NotificationTemplateService_DeleteTemplate_FullMethodName        = "/notification_template.NotificationTemplateService/DeleteTemplate"
	NotificationTemplateService_CloneTemplate_FullMethodName         = "/notification_template.NotificationTemplateService/CloneTemplate"
	NotificationTemplateService_RenderTemplate_FullMethodName        = "/notification_template.NotificationTemplateService/RenderTemplate"
	NotificationTemplateService_ValidateTemplate_FullMethodName      = "/notification_template.NotificationTemplateService/ValidateTemplate"
	NotificationTemplateService_GetAvailableVariables_FullMethodName = "/notification_template.NotificationTemplateService/GetAvailableVariables"
	NotificationTemplateService_SetDefaultTemplate_FullMethodName    = "/notification_template.NotificationTemplateService/SetDefaultTemplate"
	NotificationTemplateService_GetDefaultTemplate_FullMethodName    = "/notification_template.NotificationTemplateService/GetDefaultTemplate"
	NotificationTemplateService_PreviewTemplate_FullMethodName       = "/notification_template.NotificationTemplateService/PreviewTemplate"
)

// NotificationTemplateServiceClient is the client API for NotificationTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Notification Template service provides template management
type NotificationTemplateServiceClient interface {
	// uc_05_01_01: Create a new template
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	// uc_05_01_02: Get template by ID
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	// uc_05_01_03: List all templates with filtering
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	// uc_05_01_04: Update template
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	// uc_05_01_05: Delete template
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*Empty, error)
	// uc_05_01_06: Clone template with new name
	CloneTemplate(ctx context.Context, in *CloneTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	// uc_05_02_01: Render template with provided variables
	RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderedTemplate, error)
	// uc_05_02_02: Validate template syntax
	ValidateTemplate(ctx context.Context, in *ValidateTemplateRequest, opts ...grpc.CallOption) (*ValidationResult, error)
	// uc_05_02_03: Get available variables for template type
	GetAvailableVariables(ctx context.Context, in *GetAvailableVariablesRequest, opts ...grpc.CallOption) (*AvailableVariables, error)
	// uc_05_03_01: Set template as default for channel/type
	SetDefaultTemplate(ctx context.Context, in *SetDefaultTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	// uc_05_03_02: Get default template for channel/type
	GetDefaultTemplate(ctx context.Context, in *GetDefaultTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	// uc_05_04_01: Preview template with sample data
	PreviewTemplate(ctx context.Context, in *PreviewTemplateRequest, opts ...grpc.CallOption) (*RenderedTemplate, error)
}

type notificationTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationTemplateServiceClient(cc grpc.ClientConnInterface) NotificationTemplateServiceClient {
	return &notificationTemplateServiceClient{cc}
}

func (c *notificationTemplateServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, NotificationTemplateService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, NotificationTemplateService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, NotificationTemplateService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, NotificationTemplateService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NotificationTemplateService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) CloneTemplate(ctx context.Context, in *CloneTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, NotificationTemplateService_CloneTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderedTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderedTemplate)
	err := c.cc.Invoke(ctx, NotificationTemplateService_RenderTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) ValidateTemplate(ctx context.Context, in *ValidateTemplateRequest, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, NotificationTemplateService_ValidateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) GetAvailableVariables(ctx context.Context, in *GetAvailableVariablesRequest, opts ...grpc.CallOption) (*AvailableVariables, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailableVariables)
	err := c.cc.Invoke(ctx, NotificationTemplateService_GetAvailableVariables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) SetDefaultTemplate(ctx context.Context, in *SetDefaultTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, NotificationTemplateService_SetDefaultTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) GetDefaultTemplate(ctx context.Context, in *GetDefaultTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, NotificationTemplateService_GetDefaultTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationTemplateServiceClient) PreviewTemplate(ctx context.Context, in *PreviewTemplateRequest, opts ...grpc.CallOption) (*RenderedTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderedTemplate)
	err := c.cc.Invoke(ctx, NotificationTemplateService_PreviewTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationTemplateServiceServer is the server API for NotificationTemplateService service.
// All implementations must embed UnimplementedNotificationTemplateServiceServer
// for forward compatibility.
//
// Notification Template service provides template management
type NotificationTemplateServiceServer interface {
	// uc_05_01_01: Create a new template
	CreateTemplate(context.Context, *CreateTemplateRequest) (*Template, error)
	// uc_05_01_02: Get template by ID
	GetTemplate(context.Context, *GetTemplateRequest) (*Template, error)
	// uc_05_01_03: List all templates with filtering
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	// uc_05_01_04: Update template
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*Template, error)
	// uc_05_01_05: Delete template
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*Empty, error)
	// uc_05_01_06: Clone template with new name
	CloneTemplate(context.Context, *CloneTemplateRequest) (*Template, error)
	// uc_05_02_01: Render template with provided variables
	RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderedTemplate, error)
	// uc_05_02_02: Validate template syntax
	ValidateTemplate(context.Context, *ValidateTemplateRequest) (*ValidationResult, error)
	// uc_05_02_03: Get available variables for template type
	GetAvailableVariables(context.Context, *GetAvailableVariablesRequest) (*AvailableVariables, error)
	// uc_05_03_01: Set template as default for channel/type
	SetDefaultTemplate(context.Context, *SetDefaultTemplateRequest) (*Template, error)
	// uc_05_03_02: Get default template for channel/type
	GetDefaultTemplate(context.Context, *GetDefaultTemplateRequest) (*Template, error)
	// uc_05_04_01: Preview template with sample data
	PreviewTemplate(context.Context, *PreviewTemplateRequest) (*RenderedTemplate, error)
	mustEmbedUnimplementedNotificationTemplateServiceServer()
}

// UnimplementedNotificationTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationTemplateServiceServer struct{}

func (UnimplementedNotificationTemplateServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) CloneTemplate(context.Context, *CloneTemplateRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderedTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) ValidateTemplate(context.Context, *ValidateTemplateRequest) (*ValidationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) GetAvailableVariables(context.Context, *GetAvailableVariablesRequest) (*AvailableVariables, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableVariables not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) SetDefaultTemplate(context.Context, *SetDefaultTemplateRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) GetDefaultTemplate(context.Context, *GetDefaultTemplateRequest) (*Template, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) PreviewTemplate(context.Context, *PreviewTemplateRequest) (*RenderedTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewTemplate not implemented")
}
func (UnimplementedNotificationTemplateServiceServer) mustEmbedUnimplementedNotificationTemplateServiceServer() {
}
func (UnimplementedNotificationTemplateServiceServer) testEmbeddedByValue() {}

// UnsafeNotificationTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationTemplateServiceServer will
// result in compilation errors.
type UnsafeNotificationTemplateServiceServer interface {
	mustEmbedUnimplementedNotificationTemplateServiceServer()
}

func RegisterNotificationTemplateServiceServer(s grpc.ServiceRegistrar, srv NotificationTemplateServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationTemplateService_ServiceDesc, srv)
}

func _NotificationTemplateService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_CloneTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).CloneTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_CloneTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).CloneTemplate(ctx, req.(*CloneTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_RenderTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).RenderTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_RenderTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).RenderTemplate(ctx, req.(*RenderTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_ValidateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).ValidateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_ValidateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).ValidateTemplate(ctx, req.(*ValidateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_GetAvailableVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).GetAvailableVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_GetAvailableVariables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).GetAvailableVariables(ctx, req.(*GetAvailableVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_SetDefaultTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).SetDefaultTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_SetDefaultTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).SetDefaultTemplate(ctx, req.(*SetDefaultTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_GetDefaultTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).GetDefaultTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_GetDefaultTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).GetDefaultTemplate(ctx, req.(*GetDefaultTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationTemplateService_PreviewTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationTemplateServiceServer).PreviewTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationTemplateService_PreviewTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationTemplateServiceServer).PreviewTemplate(ctx, req.(*PreviewTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationTemplateService_ServiceDesc is the grpc.ServiceDesc for NotificationTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification_template.NotificationTemplateService",
	HandlerType: (*NotificationTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _NotificationTemplateService_CreateTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _NotificationTemplateService_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _NotificationTemplateService_ListTemplates_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _NotificationTemplateService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _NotificationTemplateService_DeleteTemplate_Handler,
		},
		{
			MethodName: "CloneTemplate",
			Handler:    _NotificationTemplateService_CloneTemplate_Handler,
		},
		{
			MethodName: "RenderTemplate",
			Handler:    _NotificationTemplateService_RenderTemplate_Handler,
		},
		{
			MethodName: "ValidateTemplate",
			Handler:    _NotificationTemplateService_ValidateTemplate_Handler,
		},
		{
			MethodName: "GetAvailableVariables",
			Handler:    _NotificationTemplateService_GetAvailableVariables_Handler,
		},
		{
			MethodName: "SetDefaultTemplate",
			Handler:    _NotificationTemplateService_SetDefaultTemplate_Handler,
		},
		{
			MethodName: "GetDefaultTemplate",
			Handler:    _NotificationTemplateService_GetDefaultTemplate_Handler,
		},
		{
			MethodName: "PreviewTemplate",
			Handler:    _NotificationTemplateService_PreviewTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notification_template.proto",
}
