// epic=09_scheduler, us=09_01_worker_management
// Scheduler service for managing check scheduling and workers

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/scheduler.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerService_RegisterWorker_FullMethodName        = "/scheduler.SchedulerService/RegisterWorker"
	SchedulerService_WorkerHeartbeat_FullMethodName       = "/scheduler.SchedulerService/WorkerHeartbeat"
	SchedulerService_UnregisterWorker_FullMethodName      = "/scheduler.SchedulerService/UnregisterWorker"
	SchedulerService_GetWorkerStatus_FullMethodName       = "/scheduler.SchedulerService/GetWorkerStatus"
	SchedulerService_ListWorkers_FullMethodName           = "/scheduler.SchedulerService/ListWorkers"
	SchedulerService_GetScheduledChecks_FullMethodName    = "/scheduler.SchedulerService/GetScheduledChecks"
	SchedulerService_GetNextCheck_FullMethodName          = "/scheduler.SchedulerService/GetNextCheck"
	SchedulerService_TriggerScheduledCheck_FullMethodName = "/scheduler.SchedulerService/TriggerScheduledCheck"
	SchedulerService_CompleteCheck_FullMethodName         = "/scheduler.SchedulerService/CompleteCheck"
	SchedulerService_ReassignOverdueChecks_FullMethodName = "/scheduler.SchedulerService/ReassignOverdueChecks"
)

// SchedulerServiceClient is the client API for SchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Scheduler service provides check scheduling management
type SchedulerServiceClient interface {
	// uc_09_01_01: Register a worker
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*Worker, error)
	// uc_09_01_02: Heartbeat from worker
	WorkerHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
	// uc_09_01_03: Unregister a worker
	UnregisterWorker(ctx context.Context, in *UnregisterWorkerRequest, opts ...grpc.CallOption) (*Empty, error)
	// uc_09_01_04: Get worker status
	GetWorkerStatus(ctx context.Context, in *GetWorkerStatusRequest, opts ...grpc.CallOption) (*Worker, error)
	// uc_09_01_05: List all workers
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// uc_09_02_03: Get scheduled checks for a time window
	GetScheduledChecks(ctx context.Context, in *GetScheduledChecksRequest, opts ...grpc.CallOption) (*ScheduledChecks, error)
	// uc_09_02_04: Get next check for a monitor
	GetNextCheck(ctx context.Context, in *GetNextCheckRequest, opts ...grpc.CallOption) (*ScheduledCheck, error)
	// uc_09_02_05: Manually trigger check
	TriggerScheduledCheck(ctx context.Context, in *TriggerScheduledCheckRequest, opts ...grpc.CallOption) (*Empty, error)
	// uc_09_02_06: Complete a scheduled check
	CompleteCheck(ctx context.Context, in *CompleteCheckRequest, opts ...grpc.CallOption) (*Empty, error)
	// uc_09_02_14: Handle overdue check reassignment
	ReassignOverdueChecks(ctx context.Context, in *ReassignOverdueChecksRequest, opts ...grpc.CallOption) (*Empty, error)
}

type schedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerServiceClient(cc grpc.ClientConnInterface) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*Worker, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Worker)
	err := c.cc.Invoke(ctx, SchedulerService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) WorkerHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_WorkerHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) UnregisterWorker(ctx context.Context, in *UnregisterWorkerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_UnregisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) GetWorkerStatus(ctx context.Context, in *GetWorkerStatusRequest, opts ...grpc.CallOption) (*Worker, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Worker)
	err := c.cc.Invoke(ctx, SchedulerService_GetWorkerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, SchedulerService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) GetScheduledChecks(ctx context.Context, in *GetScheduledChecksRequest, opts ...grpc.CallOption) (*ScheduledChecks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledChecks)
	err := c.cc.Invoke(ctx, SchedulerService_GetScheduledChecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) GetNextCheck(ctx context.Context, in *GetNextCheckRequest, opts ...grpc.CallOption) (*ScheduledCheck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduledCheck)
	err := c.cc.Invoke(ctx, SchedulerService_GetNextCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) TriggerScheduledCheck(ctx context.Context, in *TriggerScheduledCheckRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_TriggerScheduledCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) CompleteCheck(ctx context.Context, in *CompleteCheckRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_CompleteCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) ReassignOverdueChecks(ctx context.Context, in *ReassignOverdueChecksRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_ReassignOverdueChecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServiceServer is the server API for SchedulerService service.
// All implementations must embed UnimplementedSchedulerServiceServer
// for forward compatibility.
//
// Scheduler service provides check scheduling management
type SchedulerServiceServer interface {
	// uc_09_01_01: Register a worker
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*Worker, error)
	// uc_09_01_02: Heartbeat from worker
	WorkerHeartbeat(context.Context, *HeartbeatRequest) (*Empty, error)
	// uc_09_01_03: Unregister a worker
	UnregisterWorker(context.Context, *UnregisterWorkerRequest) (*Empty, error)
	// uc_09_01_04: Get worker status
	GetWorkerStatus(context.Context, *GetWorkerStatusRequest) (*Worker, error)
	// uc_09_01_05: List all workers
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// uc_09_02_03: Get scheduled checks for a time window
	GetScheduledChecks(context.Context, *GetScheduledChecksRequest) (*ScheduledChecks, error)
	// uc_09_02_04: Get next check for a monitor
	GetNextCheck(context.Context, *GetNextCheckRequest) (*ScheduledCheck, error)
	// uc_09_02_05: Manually trigger check
	TriggerScheduledCheck(context.Context, *TriggerScheduledCheckRequest) (*Empty, error)
	// uc_09_02_06: Complete a scheduled check
	CompleteCheck(context.Context, *CompleteCheckRequest) (*Empty, error)
	// uc_09_02_14: Handle overdue check reassignment
	ReassignOverdueChecks(context.Context, *ReassignOverdueChecksRequest) (*Empty, error)
	mustEmbedUnimplementedSchedulerServiceServer()
}

// UnimplementedSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServiceServer struct{}

func (UnimplementedSchedulerServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*Worker, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedSchedulerServiceServer) WorkerHeartbeat(context.Context, *HeartbeatRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerHeartbeat not implemented")
}
func (UnimplementedSchedulerServiceServer) UnregisterWorker(context.Context, *UnregisterWorkerRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterWorker not implemented")
}
func (UnimplementedSchedulerServiceServer) GetWorkerStatus(context.Context, *GetWorkerStatusRequest) (*Worker, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerStatus not implemented")
}
func (UnimplementedSchedulerServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedSchedulerServiceServer) GetScheduledChecks(context.Context, *GetScheduledChecksRequest) (*ScheduledChecks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduledChecks not implemented")
}
func (UnimplementedSchedulerServiceServer) GetNextCheck(context.Context, *GetNextCheckRequest) (*ScheduledCheck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextCheck not implemented")
}
func (UnimplementedSchedulerServiceServer) TriggerScheduledCheck(context.Context, *TriggerScheduledCheckRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerScheduledCheck not implemented")
}
func (UnimplementedSchedulerServiceServer) CompleteCheck(context.Context, *CompleteCheckRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteCheck not implemented")
}
func (UnimplementedSchedulerServiceServer) ReassignOverdueChecks(context.Context, *ReassignOverdueChecksRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReassignOverdueChecks not implemented")
}
func (UnimplementedSchedulerServiceServer) mustEmbedUnimplementedSchedulerServiceServer() {}
func (UnimplementedSchedulerServiceServer) testEmbeddedByValue()                          {}

// UnsafeSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServiceServer will
// result in compilation errors.
type UnsafeSchedulerServiceServer interface {
	mustEmbedUnimplementedSchedulerServiceServer()
}

func RegisterSchedulerServiceServer(s grpc.ServiceRegistrar, srv SchedulerServiceServer) {
	// If the following call pancis, it indicates UnimplementedSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerService_ServiceDesc, srv)
}

func _SchedulerService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_WorkerHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).WorkerHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_WorkerHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).WorkerHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_UnregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).UnregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_UnregisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).UnregisterWorker(ctx, req.(*UnregisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_GetWorkerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GetWorkerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_GetWorkerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GetWorkerStatus(ctx, req.(*GetWorkerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_GetScheduledChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduledChecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GetScheduledChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_GetScheduledChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GetScheduledChecks(ctx, req.(*GetScheduledChecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_GetNextCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GetNextCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_GetNextCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GetNextCheck(ctx, req.(*GetNextCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_TriggerScheduledCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerScheduledCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).TriggerScheduledCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_TriggerScheduledCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).TriggerScheduledCheck(ctx, req.(*TriggerScheduledCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_CompleteCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).CompleteCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_CompleteCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).CompleteCheck(ctx, req.(*CompleteCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_ReassignOverdueChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignOverdueChecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).ReassignOverdueChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_ReassignOverdueChecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).ReassignOverdueChecks(ctx, req.(*ReassignOverdueChecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerService_ServiceDesc is the grpc.ServiceDesc for SchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _SchedulerService_RegisterWorker_Handler,
		},
		{
			MethodName: "WorkerHeartbeat",
			Handler:    _SchedulerService_WorkerHeartbeat_Handler,
		},
		{
			MethodName: "UnregisterWorker",
			Handler:    _SchedulerService_UnregisterWorker_Handler,
		},
		{
			MethodName: "GetWorkerStatus",
			Handler:    _SchedulerService_GetWorkerStatus_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _SchedulerService_ListWorkers_Handler,
		},
		{
			MethodName: "GetScheduledChecks",
			Handler:    _SchedulerService_GetScheduledChecks_Handler,
		},
		{
			MethodName: "GetNextCheck",
			Handler:    _SchedulerService_GetNextCheck_Handler,
		},
		{
			MethodName: "TriggerScheduledCheck",
			Handler:    _SchedulerService_TriggerScheduledCheck_Handler,
		},
		{
			MethodName: "CompleteCheck",
			Handler:    _SchedulerService_CompleteCheck_Handler,
		},
		{
			MethodName: "ReassignOverdueChecks",
			Handler:    _SchedulerService_ReassignOverdueChecks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scheduler.proto",
}
