FROM golang:1.25-alpine AS builder
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest
COPY --from=builder /go/bin/goose /usr/local/bin/goose
RUN apk --no-cache add ca-certificates
WORKDIR /migrations
ENTRYPOINT ["goose"]
