// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher {
	mock := &EventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventPublisher is an autogenerated mock type for the eventPublisher type
type EventPublisher struct {
	mock.Mock
}

type EventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisher) EXPECT() *EventPublisher_Expecter {
	return &EventPublisher_Expecter{mock: &_m.Mock}
}

// PublishOAuthAccountLinked provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishOAuthAccountLinked(ctx context.Context, userID string, email string, provider string, providerID string) error {
	ret := _mock.Called(ctx, userID, email, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for PublishOAuthAccountLinked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, email, provider, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishOAuthAccountLinked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOAuthAccountLinked'
type EventPublisher_PublishOAuthAccountLinked_Call struct {
	*mock.Call
}

// PublishOAuthAccountLinked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
//   - provider string
//   - providerID string
func (_e *EventPublisher_Expecter) PublishOAuthAccountLinked(ctx interface{}, userID interface{}, email interface{}, provider interface{}, providerID interface{}) *EventPublisher_PublishOAuthAccountLinked_Call {
	return &EventPublisher_PublishOAuthAccountLinked_Call{Call: _e.mock.On("PublishOAuthAccountLinked", ctx, userID, email, provider, providerID)}
}

func (_c *EventPublisher_PublishOAuthAccountLinked_Call) Run(run func(ctx context.Context, userID string, email string, provider string, providerID string)) *EventPublisher_PublishOAuthAccountLinked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishOAuthAccountLinked_Call) Return(err error) *EventPublisher_PublishOAuthAccountLinked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishOAuthAccountLinked_Call) RunAndReturn(run func(ctx context.Context, userID string, email string, provider string, providerID string) error) *EventPublisher_PublishOAuthAccountLinked_Call {
	_c.Call.Return(run)
	return _c
}

// PublishSessionCreated provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishSessionCreated(ctx context.Context, userID string, email string, sessionID string, expiresAt int64) error {
	ret := _mock.Called(ctx, userID, email, sessionID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for PublishSessionCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) error); ok {
		r0 = returnFunc(ctx, userID, email, sessionID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishSessionCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishSessionCreated'
type EventPublisher_PublishSessionCreated_Call struct {
	*mock.Call
}

// PublishSessionCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
//   - sessionID string
//   - expiresAt int64
func (_e *EventPublisher_Expecter) PublishSessionCreated(ctx interface{}, userID interface{}, email interface{}, sessionID interface{}, expiresAt interface{}) *EventPublisher_PublishSessionCreated_Call {
	return &EventPublisher_PublishSessionCreated_Call{Call: _e.mock.On("PublishSessionCreated", ctx, userID, email, sessionID, expiresAt)}
}

func (_c *EventPublisher_PublishSessionCreated_Call) Run(run func(ctx context.Context, userID string, email string, sessionID string, expiresAt int64)) *EventPublisher_PublishSessionCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishSessionCreated_Call) Return(err error) *EventPublisher_PublishSessionCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishSessionCreated_Call) RunAndReturn(run func(ctx context.Context, userID string, email string, sessionID string, expiresAt int64) error) *EventPublisher_PublishSessionCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserCreated provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishUserCreated(ctx context.Context, userID string, email string) error {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishUserCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserCreated'
type EventPublisher_PublishUserCreated_Call struct {
	*mock.Call
}

// PublishUserCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
func (_e *EventPublisher_Expecter) PublishUserCreated(ctx interface{}, userID interface{}, email interface{}) *EventPublisher_PublishUserCreated_Call {
	return &EventPublisher_PublishUserCreated_Call{Call: _e.mock.On("PublishUserCreated", ctx, userID, email)}
}

func (_c *EventPublisher_PublishUserCreated_Call) Run(run func(ctx context.Context, userID string, email string)) *EventPublisher_PublishUserCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishUserCreated_Call) Return(err error) *EventPublisher_PublishUserCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishUserCreated_Call) RunAndReturn(run func(ctx context.Context, userID string, email string) error) *EventPublisher_PublishUserCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserFailedLogin provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishUserFailedLogin(ctx context.Context, userID string, email string, ip string, reason string) error {
	ret := _mock.Called(ctx, userID, email, ip, reason)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserFailedLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, email, ip, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishUserFailedLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserFailedLogin'
type EventPublisher_PublishUserFailedLogin_Call struct {
	*mock.Call
}

// PublishUserFailedLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
//   - ip string
//   - reason string
func (_e *EventPublisher_Expecter) PublishUserFailedLogin(ctx interface{}, userID interface{}, email interface{}, ip interface{}, reason interface{}) *EventPublisher_PublishUserFailedLogin_Call {
	return &EventPublisher_PublishUserFailedLogin_Call{Call: _e.mock.On("PublishUserFailedLogin", ctx, userID, email, ip, reason)}
}

func (_c *EventPublisher_PublishUserFailedLogin_Call) Run(run func(ctx context.Context, userID string, email string, ip string, reason string)) *EventPublisher_PublishUserFailedLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishUserFailedLogin_Call) Return(err error) *EventPublisher_PublishUserFailedLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishUserFailedLogin_Call) RunAndReturn(run func(ctx context.Context, userID string, email string, ip string, reason string) error) *EventPublisher_PublishUserFailedLogin_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserLocked provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishUserLocked(ctx context.Context, userID string, email string, attempts int) error {
	ret := _mock.Called(ctx, userID, email, attempts)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserLocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, userID, email, attempts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishUserLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserLocked'
type EventPublisher_PublishUserLocked_Call struct {
	*mock.Call
}

// PublishUserLocked is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
//   - attempts int
func (_e *EventPublisher_Expecter) PublishUserLocked(ctx interface{}, userID interface{}, email interface{}, attempts interface{}) *EventPublisher_PublishUserLocked_Call {
	return &EventPublisher_PublishUserLocked_Call{Call: _e.mock.On("PublishUserLocked", ctx, userID, email, attempts)}
}

func (_c *EventPublisher_PublishUserLocked_Call) Run(run func(ctx context.Context, userID string, email string, attempts int)) *EventPublisher_PublishUserLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishUserLocked_Call) Return(err error) *EventPublisher_PublishUserLocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishUserLocked_Call) RunAndReturn(run func(ctx context.Context, userID string, email string, attempts int) error) *EventPublisher_PublishUserLocked_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserLoggedIn provides a mock function for the type EventPublisher
func (_mock *EventPublisher) PublishUserLoggedIn(ctx context.Context, userID string, email string, ip string, userAgent string) error {
	ret := _mock.Called(ctx, userID, email, ip, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserLoggedIn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, email, ip, userAgent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventPublisher_PublishUserLoggedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserLoggedIn'
type EventPublisher_PublishUserLoggedIn_Call struct {
	*mock.Call
}

// PublishUserLoggedIn is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
//   - ip string
//   - userAgent string
func (_e *EventPublisher_Expecter) PublishUserLoggedIn(ctx interface{}, userID interface{}, email interface{}, ip interface{}, userAgent interface{}) *EventPublisher_PublishUserLoggedIn_Call {
	return &EventPublisher_PublishUserLoggedIn_Call{Call: _e.mock.On("PublishUserLoggedIn", ctx, userID, email, ip, userAgent)}
}

func (_c *EventPublisher_PublishUserLoggedIn_Call) Run(run func(ctx context.Context, userID string, email string, ip string, userAgent string)) *EventPublisher_PublishUserLoggedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EventPublisher_PublishUserLoggedIn_Call) Return(err error) *EventPublisher_PublishUserLoggedIn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventPublisher_PublishUserLoggedIn_Call) RunAndReturn(run func(ctx context.Context, userID string, email string, ip string, userAgent string) error) *EventPublisher_PublishUserLoggedIn_Call {
	_c.Call.Return(run)
	return _c
}
