// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewInviteOrgRepo creates a new instance of InviteOrgRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteOrgRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteOrgRepo {
	mock := &InviteOrgRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InviteOrgRepo is an autogenerated mock type for the inviteOrgRepo type
type InviteOrgRepo struct {
	mock.Mock
}

type InviteOrgRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteOrgRepo) EXPECT() *InviteOrgRepo_Expecter {
	return &InviteOrgRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type InviteOrgRepo
func (_mock *InviteOrgRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteOrgRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type InviteOrgRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *InviteOrgRepo_Expecter) GetByID(ctx interface{}, id interface{}) *InviteOrgRepo_GetByID_Call {
	return &InviteOrgRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *InviteOrgRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *InviteOrgRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteOrgRepo_GetByID_Call) Return(organization *model.Organization, err error) *InviteOrgRepo_GetByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *InviteOrgRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Organization, error)) *InviteOrgRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
