// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewInvitePublisher creates a new instance of InvitePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitePublisher {
	mock := &InvitePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InvitePublisher is an autogenerated mock type for the invitePublisher type
type InvitePublisher struct {
	mock.Mock
}

type InvitePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitePublisher) EXPECT() *InvitePublisher_Expecter {
	return &InvitePublisher_Expecter{mock: &_m.Mock}
}

// PublishInviteCreated provides a mock function for the type InvitePublisher
func (_mock *InvitePublisher) PublishInviteCreated(ctx context.Context, inv *model.Invite) error {
	ret := _mock.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for PublishInviteCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Invite) error); ok {
		r0 = returnFunc(ctx, inv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InvitePublisher_PublishInviteCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishInviteCreated'
type InvitePublisher_PublishInviteCreated_Call struct {
	*mock.Call
}

// PublishInviteCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - inv *model.Invite
func (_e *InvitePublisher_Expecter) PublishInviteCreated(ctx interface{}, inv interface{}) *InvitePublisher_PublishInviteCreated_Call {
	return &InvitePublisher_PublishInviteCreated_Call{Call: _e.mock.On("PublishInviteCreated", ctx, inv)}
}

func (_c *InvitePublisher_PublishInviteCreated_Call) Run(run func(ctx context.Context, inv *model.Invite)) *InvitePublisher_PublishInviteCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Invite
		if args[1] != nil {
			arg1 = args[1].(*model.Invite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InvitePublisher_PublishInviteCreated_Call) Return(err error) *InvitePublisher_PublishInviteCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InvitePublisher_PublishInviteCreated_Call) RunAndReturn(run func(ctx context.Context, inv *model.Invite) error) *InvitePublisher_PublishInviteCreated_Call {
	_c.Call.Return(run)
	return _c
}
