// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewInviteMembershipRepo creates a new instance of InviteMembershipRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteMembershipRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteMembershipRepo {
	mock := &InviteMembershipRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InviteMembershipRepo is an autogenerated mock type for the inviteMembershipRepo type
type InviteMembershipRepo struct {
	mock.Mock
}

type InviteMembershipRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteMembershipRepo) EXPECT() *InviteMembershipRepo_Expecter {
	return &InviteMembershipRepo_Expecter{mock: &_m.Mock}
}

// CountByOrg provides a mock function for the type InviteMembershipRepo
func (_mock *InviteMembershipRepo) CountByOrg(ctx context.Context, orgID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for CountByOrg")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, orgID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, orgID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteMembershipRepo_CountByOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByOrg'
type InviteMembershipRepo_CountByOrg_Call struct {
	*mock.Call
}

// CountByOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *InviteMembershipRepo_Expecter) CountByOrg(ctx interface{}, orgID interface{}) *InviteMembershipRepo_CountByOrg_Call {
	return &InviteMembershipRepo_CountByOrg_Call{Call: _e.mock.On("CountByOrg", ctx, orgID)}
}

func (_c *InviteMembershipRepo_CountByOrg_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *InviteMembershipRepo_CountByOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteMembershipRepo_CountByOrg_Call) Return(n int, err error) *InviteMembershipRepo_CountByOrg_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *InviteMembershipRepo_CountByOrg_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID) (int, error)) *InviteMembershipRepo_CountByOrg_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type InviteMembershipRepo
func (_mock *InviteMembershipRepo) Create(ctx context.Context, m *model.Membership) (*model.Membership, error) {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Membership) (*model.Membership, error)); ok {
		return returnFunc(ctx, m)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Membership) *model.Membership); ok {
		r0 = returnFunc(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Membership) error); ok {
		r1 = returnFunc(ctx, m)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteMembershipRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InviteMembershipRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *model.Membership
func (_e *InviteMembershipRepo_Expecter) Create(ctx interface{}, m interface{}) *InviteMembershipRepo_Create_Call {
	return &InviteMembershipRepo_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *InviteMembershipRepo_Create_Call) Run(run func(ctx context.Context, m *model.Membership)) *InviteMembershipRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Membership
		if args[1] != nil {
			arg1 = args[1].(*model.Membership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InviteMembershipRepo_Create_Call) Return(membership *model.Membership, err error) *InviteMembershipRepo_Create_Call {
	_c.Call.Return(membership, err)
	return _c
}

func (_c *InviteMembershipRepo_Create_Call) RunAndReturn(run func(ctx context.Context, m *model.Membership) (*model.Membership, error)) *InviteMembershipRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserEmail provides a mock function for the type InviteMembershipRepo
func (_mock *InviteMembershipRepo) FindByUserEmail(ctx context.Context, orgID uuid.UUID, email string) (*model.Membership, error) {
	ret := _mock.Called(ctx, orgID, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserEmail")
	}

	var r0 *model.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.Membership, error)); ok {
		return returnFunc(ctx, orgID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.Membership); ok {
		r0 = returnFunc(ctx, orgID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, orgID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteMembershipRepo_FindByUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserEmail'
type InviteMembershipRepo_FindByUserEmail_Call struct {
	*mock.Call
}

// FindByUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - email string
func (_e *InviteMembershipRepo_Expecter) FindByUserEmail(ctx interface{}, orgID interface{}, email interface{}) *InviteMembershipRepo_FindByUserEmail_Call {
	return &InviteMembershipRepo_FindByUserEmail_Call{Call: _e.mock.On("FindByUserEmail", ctx, orgID, email)}
}

func (_c *InviteMembershipRepo_FindByUserEmail_Call) Run(run func(ctx context.Context, orgID uuid.UUID, email string)) *InviteMembershipRepo_FindByUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InviteMembershipRepo_FindByUserEmail_Call) Return(membership *model.Membership, err error) *InviteMembershipRepo_FindByUserEmail_Call {
	_c.Call.Return(membership, err)
	return _c
}

func (_c *InviteMembershipRepo_FindByUserEmail_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, email string) (*model.Membership, error)) *InviteMembershipRepo_FindByUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrgAndUser provides a mock function for the type InviteMembershipRepo
func (_mock *InviteMembershipRepo) GetByOrgAndUser(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) (*model.Membership, error) {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrgAndUser")
	}

	var r0 *model.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Membership, error)); ok {
		return returnFunc(ctx, orgID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Membership); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteMembershipRepo_GetByOrgAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrgAndUser'
type InviteMembershipRepo_GetByOrgAndUser_Call struct {
	*mock.Call
}

// GetByOrgAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *InviteMembershipRepo_Expecter) GetByOrgAndUser(ctx interface{}, orgID interface{}, userID interface{}) *InviteMembershipRepo_GetByOrgAndUser_Call {
	return &InviteMembershipRepo_GetByOrgAndUser_Call{Call: _e.mock.On("GetByOrgAndUser", ctx, orgID, userID)}
}

func (_c *InviteMembershipRepo_GetByOrgAndUser_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *InviteMembershipRepo_GetByOrgAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InviteMembershipRepo_GetByOrgAndUser_Call) Return(membership *model.Membership, err error) *InviteMembershipRepo_GetByOrgAndUser_Call {
	_c.Call.Return(membership, err)
	return _c
}

func (_c *InviteMembershipRepo_GetByOrgAndUser_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) (*model.Membership, error)) *InviteMembershipRepo_GetByOrgAndUser_Call {
	_c.Call.Return(run)
	return _c
}
