// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionCreator creates a new instance of SessionCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionCreator {
	mock := &SessionCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionCreator is an autogenerated mock type for the sessionCreator type
type SessionCreator struct {
	mock.Mock
}

type SessionCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionCreator) EXPECT() *SessionCreator_Expecter {
	return &SessionCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionCreator
func (_mock *SessionCreator) Create(ctx context.Context, session *model.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *model.Session
func (_e *SessionCreator_Expecter) Create(ctx interface{}, session interface{}) *SessionCreator_Create_Call {
	return &SessionCreator_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionCreator_Create_Call) Run(run func(ctx context.Context, session *model.Session)) *SessionCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Session
		if args[1] != nil {
			arg1 = args[1].(*model.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionCreator_Create_Call) Return(err error) *SessionCreator_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionCreator_Create_Call) RunAndReturn(run func(ctx context.Context, session *model.Session) error) *SessionCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}
