// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamPublisher creates a new instance of TeamPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamPublisher {
	mock := &TeamPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamPublisher is an autogenerated mock type for the teamPublisher type
type TeamPublisher struct {
	mock.Mock
}

type TeamPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamPublisher) EXPECT() *TeamPublisher_Expecter {
	return &TeamPublisher_Expecter{mock: &_m.Mock}
}

// PublishMemberRemoved provides a mock function for the type TeamPublisher
func (_mock *TeamPublisher) PublishMemberRemoved(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for PublishMemberRemoved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamPublisher_PublishMemberRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMemberRemoved'
type TeamPublisher_PublishMemberRemoved_Call struct {
	*mock.Call
}

// PublishMemberRemoved is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
func (_e *TeamPublisher_Expecter) PublishMemberRemoved(ctx interface{}, orgID interface{}, userID interface{}) *TeamPublisher_PublishMemberRemoved_Call {
	return &TeamPublisher_PublishMemberRemoved_Call{Call: _e.mock.On("PublishMemberRemoved", ctx, orgID, userID)}
}

func (_c *TeamPublisher_PublishMemberRemoved_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID)) *TeamPublisher_PublishMemberRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamPublisher_PublishMemberRemoved_Call) Return(err error) *TeamPublisher_PublishMemberRemoved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamPublisher_PublishMemberRemoved_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID) error) *TeamPublisher_PublishMemberRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMemberRoleChanged provides a mock function for the type TeamPublisher
func (_mock *TeamPublisher) PublishMemberRoleChanged(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, oldRole model.Role, newRole model.Role) error {
	ret := _mock.Called(ctx, orgID, userID, oldRole, newRole)

	if len(ret) == 0 {
		panic("no return value specified for PublishMemberRoleChanged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.Role, model.Role) error); ok {
		r0 = returnFunc(ctx, orgID, userID, oldRole, newRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamPublisher_PublishMemberRoleChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMemberRoleChanged'
type TeamPublisher_PublishMemberRoleChanged_Call struct {
	*mock.Call
}

// PublishMemberRoleChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - userID uuid.UUID
//   - oldRole model.Role
//   - newRole model.Role
func (_e *TeamPublisher_Expecter) PublishMemberRoleChanged(ctx interface{}, orgID interface{}, userID interface{}, oldRole interface{}, newRole interface{}) *TeamPublisher_PublishMemberRoleChanged_Call {
	return &TeamPublisher_PublishMemberRoleChanged_Call{Call: _e.mock.On("PublishMemberRoleChanged", ctx, orgID, userID, oldRole, newRole)}
}

func (_c *TeamPublisher_PublishMemberRoleChanged_Call) Run(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, oldRole model.Role, newRole model.Role)) *TeamPublisher_PublishMemberRoleChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 model.Role
		if args[3] != nil {
			arg3 = args[3].(model.Role)
		}
		var arg4 model.Role
		if args[4] != nil {
			arg4 = args[4].(model.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TeamPublisher_PublishMemberRoleChanged_Call) Return(err error) *TeamPublisher_PublishMemberRoleChanged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamPublisher_PublishMemberRoleChanged_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, userID uuid.UUID, oldRole model.Role, newRole model.Role) error) *TeamPublisher_PublishMemberRoleChanged_Call {
	_c.Call.Return(run)
	return _c
}
