// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenGenerator is an autogenerated mock type for the tokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

type TokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGenerator) EXPECT() *TokenGenerator_Expecter {
	return &TokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function for the type TokenGenerator
func (_mock *TokenGenerator) GenerateTokenPair(ctx context.Context, userID uuid.UUID, email string, tier string) (string, string, error) {
	ret := _mock.Called(ctx, userID, email, tier)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (string, string, error)); ok {
		return returnFunc(ctx, userID, email, tier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) string); ok {
		r0 = returnFunc(ctx, userID, email, tier)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) string); ok {
		r1 = returnFunc(ctx, userID, email, tier)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, string) error); ok {
		r2 = returnFunc(ctx, userID, email, tier)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenGenerator_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type TokenGenerator_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - email string
//   - tier string
func (_e *TokenGenerator_Expecter) GenerateTokenPair(ctx interface{}, userID interface{}, email interface{}, tier interface{}) *TokenGenerator_GenerateTokenPair_Call {
	return &TokenGenerator_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", ctx, userID, email, tier)}
}

func (_c *TokenGenerator_GenerateTokenPair_Call) Run(run func(ctx context.Context, userID uuid.UUID, email string, tier string)) *TokenGenerator_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenGenerator_GenerateTokenPair_Call) Return(s string, s1 string, err error) *TokenGenerator_GenerateTokenPair_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *TokenGenerator_GenerateTokenPair_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, email string, tier string) (string, string, error)) *TokenGenerator_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}
