// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/infrastructure/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenJWT creates a new instance of TokenJWT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenJWT(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenJWT {
	mock := &TokenJWT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenJWT is an autogenerated mock type for the tokenJWT type
type TokenJWT struct {
	mock.Mock
}

type TokenJWT_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenJWT) EXPECT() *TokenJWT_Expecter {
	return &TokenJWT_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function for the type TokenJWT
func (_mock *TokenJWT) GenerateTokenPair(ctx context.Context, userID uuid.UUID, email string, tier string) (string, string, error) {
	ret := _mock.Called(ctx, userID, email, tier)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (string, string, error)); ok {
		return returnFunc(ctx, userID, email, tier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) string); ok {
		r0 = returnFunc(ctx, userID, email, tier)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) string); ok {
		r1 = returnFunc(ctx, userID, email, tier)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, string) error); ok {
		r2 = returnFunc(ctx, userID, email, tier)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenJWT_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type TokenJWT_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - email string
//   - tier string
func (_e *TokenJWT_Expecter) GenerateTokenPair(ctx interface{}, userID interface{}, email interface{}, tier interface{}) *TokenJWT_GenerateTokenPair_Call {
	return &TokenJWT_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", ctx, userID, email, tier)}
}

func (_c *TokenJWT_GenerateTokenPair_Call) Run(run func(ctx context.Context, userID uuid.UUID, email string, tier string)) *TokenJWT_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenJWT_GenerateTokenPair_Call) Return(s string, s1 string, err error) *TokenJWT_GenerateTokenPair_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *TokenJWT_GenerateTokenPair_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, email string, tier string) (string, string, error)) *TokenJWT_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type TokenJWT
func (_mock *TokenJWT) ValidateAccessToken(ctx context.Context, tokenStr string) (*jwt.Claims, error) {
	ret := _mock.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwt.Claims, error)); ok {
		return returnFunc(ctx, tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwt.Claims); ok {
		r0 = returnFunc(ctx, tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenJWT_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type TokenJWT_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *TokenJWT_Expecter) ValidateAccessToken(ctx interface{}, tokenStr interface{}) *TokenJWT_ValidateAccessToken_Call {
	return &TokenJWT_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, tokenStr)}
}

func (_c *TokenJWT_ValidateAccessToken_Call) Run(run func(ctx context.Context, tokenStr string)) *TokenJWT_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenJWT_ValidateAccessToken_Call) Return(claims *jwt.Claims, err error) *TokenJWT_ValidateAccessToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *TokenJWT_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, tokenStr string) (*jwt.Claims, error)) *TokenJWT_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
