//go:build bdd

// Code generated by experiments/gen_stubs.py. DO NOT EDIT.
//
// Stub-определения для BDD-шагов эпика 05_security, ещё не покрытых
// доменными реализациями. Каждый stub имеет конкретный regex (НЕ
// catch-all) и возвращает nil, чтобы godog не помечал шаг как
// undefined или pending. Реальная семантика наполняется итеративно
// по приоритету эпика — см. docs/BDD_STUB_NOTES.md.
//
// Stub'ы регистрируются в registerEpicSteps (runner.go) ПОСЛЕ доменных
// шагов, поэтому при совпадении regex доменная реализация имеет приоритет.
// Генератор отфильтровал тексты, которые уже покрыты доменными regex,
// чтобы избежать дубликатов.

package suite

import "github.com/cucumber/godog"

// RegisterStub05SecuritySteps регистрирует stub-шаги для эпика 05_security.
func RegisterStub05SecuritySteps(ctx *godog.ScenarioContext) {
	// stub: sample features/05_security/05_01_authentication.feature:507
	ctx.Step(`^пользователь успешно авторизуется через провайдер "([^"]*)"$`, func(_ string) error { return nil })
	// stub: sample features/05_security/05_01_authentication.feature:53
	ctx.Step(`^создана запись audit log об auto account creation$`, func() error { return nil })
}
