// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewInviteServicer creates a new instance of InviteServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInviteServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *InviteServicer {
	mock := &InviteServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InviteServicer is an autogenerated mock type for the inviteServicer type
type InviteServicer struct {
	mock.Mock
}

type InviteServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *InviteServicer) EXPECT() *InviteServicer_Expecter {
	return &InviteServicer_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type InviteServicer
func (_mock *InviteServicer) Accept(ctx context.Context, token uuid.UUID, authedUserEmail string, authedUserID uuid.UUID) (*model.Membership, error) {
	ret := _mock.Called(ctx, token, authedUserEmail, authedUserID)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 *model.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) (*model.Membership, error)); ok {
		return returnFunc(ctx, token, authedUserEmail, authedUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) *model.Membership); ok {
		r0 = returnFunc(ctx, token, authedUserEmail, authedUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, token, authedUserEmail, authedUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InviteServicer_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type InviteServicer_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - token uuid.UUID
//   - authedUserEmail string
//   - authedUserID uuid.UUID
func (_e *InviteServicer_Expecter) Accept(ctx interface{}, token interface{}, authedUserEmail interface{}, authedUserID interface{}) *InviteServicer_Accept_Call {
	return &InviteServicer_Accept_Call{Call: _e.mock.On("Accept", ctx, token, authedUserEmail, authedUserID)}
}

func (_c *InviteServicer_Accept_Call) Run(run func(ctx context.Context, token uuid.UUID, authedUserEmail string, authedUserID uuid.UUID)) *InviteServicer_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *InviteServicer_Accept_Call) Return(membership *model.Membership, err error) *InviteServicer_Accept_Call {
	_c.Call.Return(membership, err)
	return _c
}

func (_c *InviteServicer_Accept_Call) RunAndReturn(run func(ctx context.Context, token uuid.UUID, authedUserEmail string, authedUserID uuid.UUID) (*model.Membership, error)) *InviteServicer_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Invite provides a mock function for the type InviteServicer
func (_mock *InviteServicer) Invite(ctx context.Context, orgID uuid.UUID, inviterID uuid.UUID, email string, role model.Role) (*model.Invite, bool, error) {
	ret := _mock.Called(ctx, orgID, inviterID, email, role)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 *model.Invite
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, model.Role) (*model.Invite, bool, error)); ok {
		return returnFunc(ctx, orgID, inviterID, email, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, model.Role) *model.Invite); ok {
		r0 = returnFunc(ctx, orgID, inviterID, email, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, model.Role) bool); ok {
		r1 = returnFunc(ctx, orgID, inviterID, email, role)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, string, model.Role) error); ok {
		r2 = returnFunc(ctx, orgID, inviterID, email, role)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// InviteServicer_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type InviteServicer_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - inviterID uuid.UUID
//   - email string
//   - role model.Role
func (_e *InviteServicer_Expecter) Invite(ctx interface{}, orgID interface{}, inviterID interface{}, email interface{}, role interface{}) *InviteServicer_Invite_Call {
	return &InviteServicer_Invite_Call{Call: _e.mock.On("Invite", ctx, orgID, inviterID, email, role)}
}

func (_c *InviteServicer_Invite_Call) Run(run func(ctx context.Context, orgID uuid.UUID, inviterID uuid.UUID, email string, role model.Role)) *InviteServicer_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 model.Role
		if args[4] != nil {
			arg4 = args[4].(model.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *InviteServicer_Invite_Call) Return(invite *model.Invite, b bool, err error) *InviteServicer_Invite_Call {
	_c.Call.Return(invite, b, err)
	return _c
}

func (_c *InviteServicer_Invite_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, inviterID uuid.UUID, email string, role model.Role) (*model.Invite, bool, error)) *InviteServicer_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type InviteServicer
func (_mock *InviteServicer) Revoke(ctx context.Context, actorID uuid.UUID, inviteID uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, inviteID)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, inviteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// InviteServicer_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type InviteServicer_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - inviteID uuid.UUID
func (_e *InviteServicer_Expecter) Revoke(ctx interface{}, actorID interface{}, inviteID interface{}) *InviteServicer_Revoke_Call {
	return &InviteServicer_Revoke_Call{Call: _e.mock.On("Revoke", ctx, actorID, inviteID)}
}

func (_c *InviteServicer_Revoke_Call) Run(run func(ctx context.Context, actorID uuid.UUID, inviteID uuid.UUID)) *InviteServicer_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *InviteServicer_Revoke_Call) Return(err error) *InviteServicer_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *InviteServicer_Revoke_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, inviteID uuid.UUID) error) *InviteServicer_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
