// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raul/monitor/backend/auth-service/internal/infrastructure/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewJwtValidator creates a new instance of JwtValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtValidator {
	mock := &JwtValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JwtValidator is an autogenerated mock type for the jwtValidator type
type JwtValidator struct {
	mock.Mock
}

type JwtValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *JwtValidator) EXPECT() *JwtValidator_Expecter {
	return &JwtValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccessToken provides a mock function for the type JwtValidator
func (_mock *JwtValidator) ValidateAccessToken(ctx context.Context, tokenStr string) (*jwt.Claims, error) {
	ret := _mock.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwt.Claims, error)); ok {
		return returnFunc(ctx, tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwt.Claims); ok {
		r0 = returnFunc(ctx, tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JwtValidator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type JwtValidator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *JwtValidator_Expecter) ValidateAccessToken(ctx interface{}, tokenStr interface{}) *JwtValidator_ValidateAccessToken_Call {
	return &JwtValidator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, tokenStr)}
}

func (_c *JwtValidator_ValidateAccessToken_Call) Run(run func(ctx context.Context, tokenStr string)) *JwtValidator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JwtValidator_ValidateAccessToken_Call) Return(claims *jwt.Claims, err error) *JwtValidator_ValidateAccessToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *JwtValidator_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, tokenStr string) (*jwt.Claims, error)) *JwtValidator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
