// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamUserLookup creates a new instance of TeamUserLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamUserLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamUserLookup {
	mock := &TeamUserLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamUserLookup is an autogenerated mock type for the teamUserLookup type
type TeamUserLookup struct {
	mock.Mock
}

type TeamUserLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamUserLookup) EXPECT() *TeamUserLookup_Expecter {
	return &TeamUserLookup_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type TeamUserLookup
func (_mock *TeamUserLookup) GetByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TeamUserLookup_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TeamUserLookup_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *TeamUserLookup_Expecter) GetByID(ctx interface{}, id interface{}) *TeamUserLookup_GetByID_Call {
	return &TeamUserLookup_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TeamUserLookup_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *TeamUserLookup_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TeamUserLookup_GetByID_Call) Return(user *model.User, err error) *TeamUserLookup_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *TeamUserLookup_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.User, error)) *TeamUserLookup_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
