// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTeamServicer creates a new instance of TeamServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamServicer {
	mock := &TeamServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TeamServicer is an autogenerated mock type for the teamServicer type
type TeamServicer struct {
	mock.Mock
}

type TeamServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamServicer) EXPECT() *TeamServicer_Expecter {
	return &TeamServicer_Expecter{mock: &_m.Mock}
}

// ChangeMemberRole provides a mock function for the type TeamServicer
func (_mock *TeamServicer) ChangeMemberRole(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID, newRole model.Role) error {
	ret := _mock.Called(ctx, orgID, actorUserID, targetUserID, newRole)

	if len(ret) == 0 {
		panic("no return value specified for ChangeMemberRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, model.Role) error); ok {
		r0 = returnFunc(ctx, orgID, actorUserID, targetUserID, newRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamServicer_ChangeMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeMemberRole'
type TeamServicer_ChangeMemberRole_Call struct {
	*mock.Call
}

// ChangeMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - actorUserID uuid.UUID
//   - targetUserID uuid.UUID
//   - newRole model.Role
func (_e *TeamServicer_Expecter) ChangeMemberRole(ctx interface{}, orgID interface{}, actorUserID interface{}, targetUserID interface{}, newRole interface{}) *TeamServicer_ChangeMemberRole_Call {
	return &TeamServicer_ChangeMemberRole_Call{Call: _e.mock.On("ChangeMemberRole", ctx, orgID, actorUserID, targetUserID, newRole)}
}

func (_c *TeamServicer_ChangeMemberRole_Call) Run(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID, newRole model.Role)) *TeamServicer_ChangeMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 model.Role
		if args[4] != nil {
			arg4 = args[4].(model.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TeamServicer_ChangeMemberRole_Call) Return(err error) *TeamServicer_ChangeMemberRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamServicer_ChangeMemberRole_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID, newRole model.Role) error) *TeamServicer_ChangeMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveOrganization provides a mock function for the type TeamServicer
func (_mock *TeamServicer) LeaveOrganization(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID) error {
	ret := _mock.Called(ctx, orgID, actorUserID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveOrganization")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orgID, actorUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamServicer_LeaveOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveOrganization'
type TeamServicer_LeaveOrganization_Call struct {
	*mock.Call
}

// LeaveOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - actorUserID uuid.UUID
func (_e *TeamServicer_Expecter) LeaveOrganization(ctx interface{}, orgID interface{}, actorUserID interface{}) *TeamServicer_LeaveOrganization_Call {
	return &TeamServicer_LeaveOrganization_Call{Call: _e.mock.On("LeaveOrganization", ctx, orgID, actorUserID)}
}

func (_c *TeamServicer_LeaveOrganization_Call) Run(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID)) *TeamServicer_LeaveOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TeamServicer_LeaveOrganization_Call) Return(err error) *TeamServicer_LeaveOrganization_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamServicer_LeaveOrganization_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID) error) *TeamServicer_LeaveOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type TeamServicer
func (_mock *TeamServicer) ListMembers(ctx context.Context, orgID uuid.UUID, page int, pageSize int) ([]*model.Membership, int, error) {
	ret := _mock.Called(ctx, orgID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []*model.Membership
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*model.Membership, int, error)); ok {
		return returnFunc(ctx, orgID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*model.Membership); ok {
		r0 = returnFunc(ctx, orgID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, orgID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, orgID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TeamServicer_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type TeamServicer_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - page int
//   - pageSize int
func (_e *TeamServicer_Expecter) ListMembers(ctx interface{}, orgID interface{}, page interface{}, pageSize interface{}) *TeamServicer_ListMembers_Call {
	return &TeamServicer_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, orgID, page, pageSize)}
}

func (_c *TeamServicer_ListMembers_Call) Run(run func(ctx context.Context, orgID uuid.UUID, page int, pageSize int)) *TeamServicer_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TeamServicer_ListMembers_Call) Return(memberships []*model.Membership, n int, err error) *TeamServicer_ListMembers_Call {
	_c.Call.Return(memberships, n, err)
	return _c
}

func (_c *TeamServicer_ListMembers_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, page int, pageSize int) ([]*model.Membership, int, error)) *TeamServicer_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function for the type TeamServicer
func (_mock *TeamServicer) RemoveMember(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID) error {
	ret := _mock.Called(ctx, orgID, actorUserID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orgID, actorUserID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamServicer_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type TeamServicer_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - actorUserID uuid.UUID
//   - targetUserID uuid.UUID
func (_e *TeamServicer_Expecter) RemoveMember(ctx interface{}, orgID interface{}, actorUserID interface{}, targetUserID interface{}) *TeamServicer_RemoveMember_Call {
	return &TeamServicer_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, actorUserID, targetUserID)}
}

func (_c *TeamServicer_RemoveMember_Call) Run(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID)) *TeamServicer_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TeamServicer_RemoveMember_Call) Return(err error) *TeamServicer_RemoveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamServicer_RemoveMember_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID) error) *TeamServicer_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// TransferOwnership provides a mock function for the type TeamServicer
func (_mock *TeamServicer) TransferOwnership(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID) error {
	ret := _mock.Called(ctx, orgID, actorUserID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwnership")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orgID, actorUserID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TeamServicer_TransferOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferOwnership'
type TeamServicer_TransferOwnership_Call struct {
	*mock.Call
}

// TransferOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
//   - actorUserID uuid.UUID
//   - targetUserID uuid.UUID
func (_e *TeamServicer_Expecter) TransferOwnership(ctx interface{}, orgID interface{}, actorUserID interface{}, targetUserID interface{}) *TeamServicer_TransferOwnership_Call {
	return &TeamServicer_TransferOwnership_Call{Call: _e.mock.On("TransferOwnership", ctx, orgID, actorUserID, targetUserID)}
}

func (_c *TeamServicer_TransferOwnership_Call) Run(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID)) *TeamServicer_TransferOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TeamServicer_TransferOwnership_Call) Return(err error) *TeamServicer_TransferOwnership_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TeamServicer_TransferOwnership_Call) RunAndReturn(run func(ctx context.Context, orgID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID) error) *TeamServicer_TransferOwnership_Call {
	_c.Call.Return(run)
	return _c
}
