// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/raul/monitor/backend/auth-service/internal/service/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenServicer creates a new instance of TokenServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenServicer {
	mock := &TokenServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenServicer is an autogenerated mock type for the tokenServicer type
type TokenServicer struct {
	mock.Mock
}

type TokenServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenServicer) EXPECT() *TokenServicer_Expecter {
	return &TokenServicer_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function for the type TokenServicer
func (_mock *TokenServicer) Logout(ctx context.Context, userID uuid.UUID, refreshToken string, sessionID string, ipAddress string, userAgent string) error {
	ret := _mock.Called(ctx, userID, refreshToken, sessionID, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, refreshToken, sessionID, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenServicer_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type TokenServicer_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refreshToken string
//   - sessionID string
//   - ipAddress string
//   - userAgent string
func (_e *TokenServicer_Expecter) Logout(ctx interface{}, userID interface{}, refreshToken interface{}, sessionID interface{}, ipAddress interface{}, userAgent interface{}) *TokenServicer_Logout_Call {
	return &TokenServicer_Logout_Call{Call: _e.mock.On("Logout", ctx, userID, refreshToken, sessionID, ipAddress, userAgent)}
}

func (_c *TokenServicer_Logout_Call) Run(run func(ctx context.Context, userID uuid.UUID, refreshToken string, sessionID string, ipAddress string, userAgent string)) *TokenServicer_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *TokenServicer_Logout_Call) Return(err error) *TokenServicer_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenServicer_Logout_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, refreshToken string, sessionID string, ipAddress string, userAgent string) error) *TokenServicer_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type TokenServicer
func (_mock *TokenServicer) RefreshToken(ctx context.Context, req *dto.RefreshTokenRequest, ipAddress string, userAgent string) (*dto.AuthResponse, error) {
	ret := _mock.Called(ctx, req, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RefreshTokenRequest, string, string) (*dto.AuthResponse, error)); ok {
		return returnFunc(ctx, req, ipAddress, userAgent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.RefreshTokenRequest, string, string) *dto.AuthResponse); ok {
		r0 = returnFunc(ctx, req, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.RefreshTokenRequest, string, string) error); ok {
		r1 = returnFunc(ctx, req, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServicer_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type TokenServicer_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.RefreshTokenRequest
//   - ipAddress string
//   - userAgent string
func (_e *TokenServicer_Expecter) RefreshToken(ctx interface{}, req interface{}, ipAddress interface{}, userAgent interface{}) *TokenServicer_RefreshToken_Call {
	return &TokenServicer_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req, ipAddress, userAgent)}
}

func (_c *TokenServicer_RefreshToken_Call) Run(run func(ctx context.Context, req *dto.RefreshTokenRequest, ipAddress string, userAgent string)) *TokenServicer_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.RefreshTokenRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.RefreshTokenRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenServicer_RefreshToken_Call) Return(authResponse *dto.AuthResponse, err error) *TokenServicer_RefreshToken_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *TokenServicer_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, req *dto.RefreshTokenRequest, ipAddress string, userAgent string) (*dto.AuthResponse, error)) *TokenServicer_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type TokenServicer
func (_mock *TokenServicer) ValidateToken(ctx context.Context, accessToken string) (*dto.ValidateTokenResponse, error) {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *dto.ValidateTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.ValidateTokenResponse, error)); ok {
		return returnFunc(ctx, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.ValidateTokenResponse); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ValidateTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenServicer_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type TokenServicer_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *TokenServicer_Expecter) ValidateToken(ctx interface{}, accessToken interface{}) *TokenServicer_ValidateToken_Call {
	return &TokenServicer_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, accessToken)}
}

func (_c *TokenServicer_ValidateToken_Call) Run(run func(ctx context.Context, accessToken string)) *TokenServicer_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenServicer_ValidateToken_Call) Return(validateTokenResponse *dto.ValidateTokenResponse, err error) *TokenServicer_ValidateToken_Call {
	_c.Call.Return(validateTokenResponse, err)
	return _c
}

func (_c *TokenServicer_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, accessToken string) (*dto.ValidateTokenResponse, error)) *TokenServicer_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
