// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/raul/monitor/backend/auth-service/internal/service/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewUserServicer creates a new instance of UserServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServicer {
	mock := &UserServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserServicer is an autogenerated mock type for the userServicer type
type UserServicer struct {
	mock.Mock
}

type UserServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServicer) EXPECT() *UserServicer_Expecter {
	return &UserServicer_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type UserServicer
func (_mock *UserServicer) GetUser(ctx context.Context, req *dto.GetUserRequest) (*dto.GetUserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *dto.GetUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetUserRequest) (*dto.GetUserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.GetUserRequest) *dto.GetUserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.GetUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServicer_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserServicer_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.GetUserRequest
func (_e *UserServicer_Expecter) GetUser(ctx interface{}, req interface{}) *UserServicer_GetUser_Call {
	return &UserServicer_GetUser_Call{Call: _e.mock.On("GetUser", ctx, req)}
}

func (_c *UserServicer_GetUser_Call) Run(run func(ctx context.Context, req *dto.GetUserRequest)) *UserServicer_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.GetUserRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.GetUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServicer_GetUser_Call) Return(getUserResponse *dto.GetUserResponse, err error) *UserServicer_GetUser_Call {
	_c.Call.Return(getUserResponse, err)
	return _c
}

func (_c *UserServicer_GetUser_Call) RunAndReturn(run func(ctx context.Context, req *dto.GetUserRequest) (*dto.GetUserResponse, error)) *UserServicer_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// LockAccount provides a mock function for the type UserServicer
func (_mock *UserServicer) LockAccount(ctx context.Context, req *dto.LockAccountRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LockAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LockAccountRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserServicer_LockAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockAccount'
type UserServicer_LockAccount_Call struct {
	*mock.Call
}

// LockAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.LockAccountRequest
func (_e *UserServicer_Expecter) LockAccount(ctx interface{}, req interface{}) *UserServicer_LockAccount_Call {
	return &UserServicer_LockAccount_Call{Call: _e.mock.On("LockAccount", ctx, req)}
}

func (_c *UserServicer_LockAccount_Call) Run(run func(ctx context.Context, req *dto.LockAccountRequest)) *UserServicer_LockAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.LockAccountRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.LockAccountRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServicer_LockAccount_Call) Return(err error) *UserServicer_LockAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserServicer_LockAccount_Call) RunAndReturn(run func(ctx context.Context, req *dto.LockAccountRequest) error) *UserServicer_LockAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockAccount provides a mock function for the type UserServicer
func (_mock *UserServicer) UnlockAccount(ctx context.Context, req *dto.UnlockAccountRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UnlockAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UnlockAccountRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserServicer_UnlockAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockAccount'
type UserServicer_UnlockAccount_Call struct {
	*mock.Call
}

// UnlockAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.UnlockAccountRequest
func (_e *UserServicer_Expecter) UnlockAccount(ctx interface{}, req interface{}) *UserServicer_UnlockAccount_Call {
	return &UserServicer_UnlockAccount_Call{Call: _e.mock.On("UnlockAccount", ctx, req)}
}

func (_c *UserServicer_UnlockAccount_Call) Run(run func(ctx context.Context, req *dto.UnlockAccountRequest)) *UserServicer_UnlockAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UnlockAccountRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UnlockAccountRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServicer_UnlockAccount_Call) Return(err error) *UserServicer_UnlockAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserServicer_UnlockAccount_Call) RunAndReturn(run func(ctx context.Context, req *dto.UnlockAccountRequest) error) *UserServicer_UnlockAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type UserServicer
func (_mock *UserServicer) UpdateUser(ctx context.Context, req *dto.UpdateUserRequest) (*dto.GetUserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *dto.GetUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdateUserRequest) (*dto.GetUserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UpdateUserRequest) *dto.GetUserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UpdateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServicer_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserServicer_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.UpdateUserRequest
func (_e *UserServicer_Expecter) UpdateUser(ctx interface{}, req interface{}) *UserServicer_UpdateUser_Call {
	return &UserServicer_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, req)}
}

func (_c *UserServicer_UpdateUser_Call) Run(run func(ctx context.Context, req *dto.UpdateUserRequest)) *UserServicer_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UpdateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServicer_UpdateUser_Call) Return(getUserResponse *dto.GetUserResponse, err error) *UserServicer_UpdateUser_Call {
	_c.Call.Return(getUserResponse, err)
	return _c
}

func (_c *UserServicer_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, req *dto.UpdateUserRequest) (*dto.GetUserResponse, error)) *UserServicer_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
