// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// NewChannelOpener creates a new instance of ChannelOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelOpener {
	mock := &ChannelOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChannelOpener is an autogenerated mock type for the channelOpener type
type ChannelOpener struct {
	mock.Mock
}

type ChannelOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelOpener) EXPECT() *ChannelOpener_Expecter {
	return &ChannelOpener_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function for the type ChannelOpener
func (_mock *ChannelOpener) Channel() (*amqp091.Channel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 *amqp091.Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*amqp091.Channel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *amqp091.Channel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ChannelOpener_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type ChannelOpener_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *ChannelOpener_Expecter) Channel() *ChannelOpener_Channel_Call {
	return &ChannelOpener_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *ChannelOpener_Channel_Call) Run(run func()) *ChannelOpener_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelOpener_Channel_Call) Return(channel *amqp091.Channel, err error) *ChannelOpener_Channel_Call {
	_c.Call.Return(channel, err)
	return _c
}

func (_c *ChannelOpener_Channel_Call) RunAndReturn(run func() (*amqp091.Channel, error)) *ChannelOpener_Channel_Call {
	_c.Call.Return(run)
	return _c
}
